version: "1.0"
customer: finnplay
argocd:
  server: argocd.tooling.test.finnplay.k8s.shockmedia.nl
jenkins:
  server: http://localhost:8080
  seedJob:
    name: gitops-seed-job
    folder: ""
  deploymentJobsDirectory: deployments
slack:
  webhookUrl: https://hooks.slack.com/services/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
repositories:
  helm: oci://ghcr.io/finnplay
  distribution: https://github.com/dmitrikeler/distribution-gitops-test.git
git:
  branch: master
