version: "1.0"
customer: finnplay
argocd:
  server: argocd.tooling.test.finnplay.k8s.shockmedia.nl
jenkins:
  server: http://localhost:8080
  seedJob:
    name: gitops-seed-job
    folder: ""
  deploymentJobsDirectory: deployments
repositories:
  helm: oci://helm.finnplay.net/finnplay
  distribution: https://github.com/dmitrikeler/distribution-gitops-test.git
git:
  branch: master
