name: dev
description: Dev Environment
config:
  argocd:
    server: argocd.tooling.test.finnplay.k8s.shockmedia.nl
  repositories:
    helm: oci://ghcr.io/finnplay
    distribution: https://github.com/dmitrikeler/distribution-gitops-test.git
  jenkins:
    server: http://localhost:8080
  slack:
    webhookUrl: https://hooks.slack.com/services/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
    lastValidated: 2025-09-11T15:22:24.826Z
  argocdNamespace: argocd
  argocdProject: finnplay-dev
applications:
- name: titan-platform
  version: 2.71.0-rc.4
  enabled: false
  valueFiles:
  - backoffice-values.yaml
  - fe-1-values.yaml
  - fe-2-values.yaml
  - fe-3-values.yaml
  - fe-4-values.yaml
  - fe-5-values.yaml
  - game-provider-api-values.yaml
  - game-provider-consumer-values.yaml
  - payment-provider-api-values.yaml
  - platform-bo-api-values.yaml
  - platform-consumer-1-values.yaml
  - platform-language-1-values.yaml
  - platform-language-2-values.yaml
  - platform-language-3-values.yaml
  - platform-language-4-values.yaml
  - platform-language-5-values.yaml
  - platform-language-consumer-values.yaml
  - platform-limit-values.yaml
  - platform-player-values.yaml
  - platform-rest-api-1-values.yaml
  - platform-rest-api-2-values.yaml
  - platform-rest-api-3-values.yaml
  - platform-rest-api-4-values.yaml
  - platform-rest-api-5-values.yaml
  - platform-storage-values.yaml
  - platform-task-values.yaml
  - platform-tool-values.yaml
  - platform-transaction-proxy-values.yaml
  - platform-webhook-values.yaml
  - titan-platform-values.yaml
- name: titan-support-services
  version: 2.63.0+build.1
  enabled: false
  valueFiles:
  - activemq-values.yaml
  - apache-values.yaml
  - consul-values.yaml
  - cron-task-report-values.yaml
  - cron-task-values.yaml
  - gateway-values.yaml
  - nginx-values.yaml
  - redis-values.yaml
  - titan-support-services-values.yaml
