name: dev
description: Dev Environment
customer: finnplay
kubernetes:
  namespace: finnplay-helm
config:
  argocd:
    server: argocd.tooling.test.finnplay.k8s.shockmedia.nl
    namespace: finnplay-helm
    project: finnplay-helm
  repositories:
    helm: helm.finnplay.net/finnplay
    distribution: https://github.com/dmitrikeler/distribution-gitops-test.git
  jenkins:
    server: http://localhost:8080
applications:
  - name: titan-support-services
    version: 2.63.0+build.2
    enabled: true
    valueFiles:
      - activemq-values.yaml
      - apache-values.yaml
      - consul-values.yaml
      - cron-task-report-values.yaml
      - cron-task-values.yaml
      - gateway-values.yaml
      - nginx-values.yaml
      - redis-values.yaml
      - titan-support-services-values.yaml
