fe-1:
  enabled: true
  nameOverride: "frontend-CHANGE_ME_CUSTOMER_ID"  # Example: frontend-prod1ks
  app:
    image:
      tag: "CHANGE_ME_FRONTEND_TAG"  # Example: 1.83.0 (update from dev version)
      pullPolicy: Always
    localConfigMaps:
      application-vars:
        # API URL should match the platform-rest-api nameOverride above
        apiUrl: "http://platform-rest-api-CHANGE_ME_CUSTOMER_ID-main/api"
        # Consul service name should match nameOverride above
        consulServiceName: "frontend-CHANGE_ME_CUSTOMER_ID"