platform-language-1:
  enabled: true
  nameOverride: platform-language
  app:
    image:
      tag: "CHANGE_ME_PLATFORM_LANGUAGE_TAG"  # Example: 2.69.0 (change from 2.69-SNAPSHOT for prod)
      pullPolicy: Always
    localConfigMaps:
      application-vars:
        source: "CHANGE_ME_SOURCE"
        placeHolderSource: "CHANGE_ME_PLACE_HOLDER_SOURCE"
        siteId: "CHANGE_ME_LANGUAGE_SITE_ID"  # Example: 95