platform-rest-api-1:
  enabled: true
  nameOverride: platform-rest-api-CHANGE_ME_CUSTOMER_ID
  app:
    image:
      tag: CHANGE_ME_PLATFORM_REST_API_TAG
      pullPolicy: Always
    resources:
      requests:
        cpu: 100m
        memory: 2Gi
      limits:
        cpu: 4000m
        memory: 8Gi
    localConfigMaps:
      application-vars:
        springCloudConsulDiscoveryServiceName: platform-rest-api-CHANGE_ME_CUSTOMER_ID
        siteId: CHANGE_ME_REST_API_SITE_ID
        xBillfoldSiteId: CHANGE_ME_BILLFOLD_SITE_ID
