platform-tool:
  app:
    image:
      tag: "CHANGE_ME_PLATFORM_TOOL_TAG"  # Example: 2.69.0 (change from 2.69-SNAPSHOT for prod)
      pullPolicy: Always
    localConfigMaps:
      application-vars:
        initDb: false  # Usually false for production environments