apache:
  enabled: true
  app:
    localConfigMaps:
      application-vars:
        domainName: "CHANGE_ME_DOMAIN_NAME"  # Example: finnplay.net
        customer: "CHANGE_ME_CUSTOMER_ID"  # Example: prod1ks
        environment: "CHANGE_ME_ENVIRONMENT"  # Example: prod
        boRegisteredSites: "CHANGE_ME_CUSTOMER_ID"  # Should match customer above
        webSiteName: "CHANGE_ME_CUSTOMER_ID"  # Should match customer above
        webSiteId: 101
        webApacheServerName: "CHANGE_ME_CUSTOMER_ID.CHANGE_ME_DOMAIN_NAME"  # Example: prod1ks.finnplay.net
        webApacheServerAlias: "CHANGE_ME_CUSTOMER_ID.CHANGE_ME_DOMAIN_NAME"
        boApacheServerName: "bo-CHANGE_ME_CUSTOMER_ID.CHANGE_ME_DOMAIN_NAME"  # Example: bo-prod1ks.finnplay.net
        boApacheServerAlias: "bo-CHANGE_ME_CUSTOMER_ID.CHANGE_ME_DOMAIN_NAME"
        platformApacheServerName: "limit-CHANGE_ME_CUSTOMER_ID.CHANGE_ME_DOMAIN_NAME"
        platformApacheServerAlias: "limit-CHANGE_ME_CUSTOMER_ID.CHANGE_ME_DOMAIN_NAME"
        apisApacheServerName: "apis-CHANGE_ME_CUSTOMER_ID.CHANGE_ME_DOMAIN_NAME"
        apisApacheServerAlias: "apis-CHANGE_ME_CUSTOMER_ID.CHANGE_ME_DOMAIN_NAME"
        statusApacheServerName: "payment-CHANGE_ME_CUSTOMER_ID.CHANGE_ME_DOMAIN_NAME"
        statusApacheServerAlias: "payment-CHANGE_ME_CUSTOMER_ID.CHANGE_ME_DOMAIN_NAME"
        titanVersion2.47: true

  ingress:
    enabled: true
    additionalAnnotations:
      nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/ssl-verify: "false"
      nginx.ingress.kubernetes.io/whitelist-source-range: "CHANGE_ME_IP_WHITELIST"  # Example: 192.168.1.0/24,10.0.0.0/8

    hosts:
      - host: "CHANGE_ME_CUSTOMER_ID.CHANGE_ME_DOMAIN_NAME"  # Example: prod1ks.finnplay.net
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: https
                port:
                  number: 443
      - host: "apis-CHANGE_ME_CUSTOMER_ID.CHANGE_ME_DOMAIN_NAME"
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: https
                port:
                  number: 443
      - host: "payment-CHANGE_ME_CUSTOMER_ID.CHANGE_ME_DOMAIN_NAME"
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: https
                port:
                  number: 443
      - host: "bo-CHANGE_ME_CUSTOMER_ID.CHANGE_ME_DOMAIN_NAME"
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: https
                port:
                  number: 443
      - host: "limit-CHANGE_ME_CUSTOMER_ID.CHANGE_ME_DOMAIN_NAME"
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: https
                port:
                  number: 443

    tls:
      - hosts:
          - "CHANGE_ME_CUSTOMER_ID.CHANGE_ME_DOMAIN_NAME"
          - "bo-CHANGE_ME_CUSTOMER_ID.CHANGE_ME_DOMAIN_NAME"
          - "apis-CHANGE_ME_CUSTOMER_ID.CHANGE_ME_DOMAIN_NAME"
          - "payment-CHANGE_ME_CUSTOMER_ID.CHANGE_ME_DOMAIN_NAME"
          - "limit-CHANGE_ME_CUSTOMER_ID.CHANGE_ME_DOMAIN_NAME"
        secretName: "CHANGE_ME_INGRESS_TLS_WILDCARD_KEYPAIR_SECRET_NAME" # pragma: allowlist secret