name: prod
description: Prod Environment
config:
  argocd:
    server: argocd.tooling.test.finnplay.k8s.shockmedia.nl
    namespace: finnplay-prod
    project: finnplay-prod
  repositories:
    helm: oci://ghcr.io/finnplay
    distribution: https://github.com/dmitrikeler/distribution-gitops-test.git
  jenkins:
    server: http://localhost:8080
  slack:
    webhookUrl: https://hooks.slack.com/services/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
applications:
  - name: titan-support-services
    version: 2.63.0+build.1
    enabled: true
    valueFiles:
      - activemq-values.yaml
      - apache-values.yaml
      - consul-values.yaml
      - cron-task-report-values.yaml
      - cron-task-values.yaml
      - gateway-values.yaml
      - nginx-values.yaml
      - redis-values.yaml
      - titan-support-services-values.yaml
