---
# =============================================================================
# TITAN Platform - Configuration Template
# =============================================================================
# This file contains skeleton values for the TITAN Platform deployment.
#
# ⚠️  IMPORTANT: You MUST customize the values marked with CHANGE_ME before deployment!
#
# Common customizations needed:
# 1. Update secret store name for your environment
# 2. Configure database connection details with correct hosts and database names
# 3. Update site IDs and customer-specific configurations
# 4. Configure hostnames and ingress settings
# 5. Review service enablement settings
# =============================================================================

# Platform service enablement - review and adjust for your environment
game-provider-consumer:
  enabled: false
platform-language-consumer:
  enabled: true
platform-storage:
  enabled: false

# Rest API instances - enable as needed for your load requirements
platform-rest-api-1:
  enabled: true
platform-rest-api-2:
  enabled: false
platform-rest-api-3:
  enabled: false
platform-rest-api-4:
  enabled: false
platform-rest-api-5:
  enabled: false

# Language service instances - enable as needed for your load requirements
platform-language-1:
  enabled: true
platform-language-2:
  enabled: false
platform-language-3:
  enabled: false
platform-language-4:
  enabled: false
platform-language-5:
  enabled: false

# Frontend instances - enable as needed for your load requirements
fe-1:
  enabled: true
fe-2:
  enabled: false
fe-3:
  enabled: false
fe-4:
  enabled: false
fe-5:
  enabled: false

# Webhook
platform-webhook:
  enabled: false

global:
  dockerDefaults:
    dockerRegistryUrlTitan: docker-new.finnplay.net

  secretDefaults:
    secretStoreName: "CHANGE_ME_SECRET_STORE_NAME"  # Example: finnplay-prod-secretstore
    secretStoreKind: SecretStore # pragma: allowlist secret

globalConfigMaps:
  global-db-vars:
    dbHost: "CHANGE_ME_DB_HOST"  # Example: 10.0.3.74
    dbName: "CHANGE_ME_DB_NAME"  # Example: titan_prod_k8s

  global-db-read-vars:
    readDbHost: "CHANGE_ME_READ_DB_HOST"  # Example: 10.0.3.74
    readDbName: "CHANGE_ME_READ_DB_NAME"  # Example: titan_prod_k8s
    storageDbHost: "CHANGE_ME_STORAGE_DB_HOST"  # Example: 10.0.3.74
    storageDbName: "CHANGE_ME_STORAGE_DB_NAME"  # Example: titan_prod_k8s

  global-site-id-vars:
    siteId: "CHANGE_ME_SITE_ID"  # Example: 95
    siteIdsAndNames: "CHANGE_ME_SITE_ID:CHANGE_ME_SITE_NAME"  # Example: 120:titan_prod_k8s

customConfigMaps:
  platform-limit-spring-datasource-url:
    dbName: "CHANGE_ME_LIMIT_DB_NAME"  # Example: titan_limit_prod_k8s
  platform-player-spring-datasource-url:
    dbName: "CHANGE_ME_PLAYER_DB_NAME"  # Example: titan_player_prod_k8s

## Platform-tool
platform-tool:
  app:
    image:
      tag: "CHANGE_ME_PLATFORM_TOOL_TAG"  # Example: 2.69.0 (change from 2.69-SNAPSHOT for prod)
      pullPolicy: Always
    localConfigMaps:
      application-vars:
        initDb: false  # Usually false for production environments

# Platform-task
platform-task:
  app:
    image:
      tag: "CHANGE_ME_PLATFORM_TASK_TAG"  # Example: 2.69.0 (change from 2.69-SNAPSHOT for prod)
      pullPolicy: Always
  localConfigMaps:
    application-vars:
      siteId: "CHANGE_ME_TASK_SITE_ID"  # Example: 101

# Platform-consumer
platform-consumer-1:
  nameOverride: platform-consumer
  app:
    image:
      tag: "CHANGE_ME_PLATFORM_CONSUMER_TAG"  # Example: 2.69.0 (change from 2.69-SNAPSHOT for prod)
      pullPolicy: Always

# Platform-bo-api
platform-bo-api:
  app:
    image:
      tag: "CHANGE_ME_PLATFORM_BO_API_TAG"  # Example: 2.69.0 (change from 2.69-SNAPSHOT for prod)
      pullPolicy: Always

## Platform-language-consumer
platform-language-consumer:
  app:
    image:
      tag: "CHANGE_ME_PLATFORM_LANG_CONSUMER_TAG"  # Example: 2.69.0 (change from 2.69-SNAPSHOT for prod)
      pullPolicy: Always

# Platform-limit
platform-limit:
  app:
    image:
      tag: "CHANGE_ME_PLATFORM_LIMIT_TAG"  # Example: 2.41.0 (change from 2.41-SNAPSHOT for prod)
      pullPolicy: Always
    localConfigMaps:
      application-vars:
        javaOpts: "-Xmx1G -Xms1G -XX:+UseG1GC"

# Platform-player
platform-player:
  app:
    image:
      tag: "CHANGE_ME_PLATFORM_PLAYER_TAG"  # Example: 2.25.0 (change from 2.25-SNAPSHOT for prod)
      pullPolicy: Always

# Platform-transaction-proxy
platform-transaction-proxy:
  app:
    image:
      tag: "CHANGE_ME_PLATFORM_TX_PROXY_TAG"  # Example: 2.20.0 (change from 2.20-SNAPSHOT for prod)
      pullPolicy: Always

# Game-provider-api
game-provider-api:
  app:
    image:
      tag: "CHANGE_ME_GAME_PROVIDER_API_TAG"  # Example: 2.69.0 (change from 2.69-SNAPSHOT for prod)
      pullPolicy: Always

# Payment-provider-api
payment-provider-api:
  app:
    image:
      tag: "CHANGE_ME_PAYMENT_PROVIDER_API_TAG"  # Example: 2.69.0 (change from 2.69-SNAPSHOT for prod)
      pullPolicy: Always

# Backoffice
backoffice:
  app:
    image:
      tag: "CHANGE_ME_BACKOFFICE_TAG"  # Example: 2.69.0 (change from 2.69-SNAPSHOT for prod)
      pullPolicy: Always
    localConfigMaps:
      application-vars:
        javaOpts: -Xms10G -Xmx10G -XX:+UseG1GC
        LOG_APPENDER: CONSOLE

# Platform-language
platform-language-1:
  nameOverride: platform-language
  app:
    image:
      tag: "CHANGE_ME_PLATFORM_LANGUAGE_TAG"  # Example: 2.69.0 (change from 2.69-SNAPSHOT for prod)
      pullPolicy: Always
    localConfigMaps:
      application-vars:
        source: "CHANGE_ME_SOURCE"
        placeHolderSource: "CHANGE_ME_PLACE_HOLDER_SOURCE"
        siteId: "CHANGE_ME_LANGUAGE_SITE_ID"  # Example: 95

# Platform-rest-api-1
platform-rest-api-1:
  nameOverride: "platform-rest-api-CHANGE_ME_CUSTOMER_ID"  # Example: platform-rest-api-prod1ks
  app:
    image:
      tag: "CHANGE_ME_PLATFORM_REST_API_TAG"  # Example: 2.69.0 (change from 2.69-SNAPSHOT for prod)
      pullPolicy: Always
    resources:
      requests:
        cpu: "100m"
        memory: "2Gi"
      limits:
        cpu: "4000m"
        memory: "8Gi"
    localConfigMaps:
      application-vars:
        springCloudConsulDiscoveryServiceName: "platform-rest-api-CHANGE_ME_CUSTOMER_ID"  # Should match nameOverride
        siteId: "CHANGE_ME_REST_API_SITE_ID"  # Example: 95
        xBillfoldSiteId: "CHANGE_ME_BILLFOLD_SITE_ID"  # Example: 95

# Frontend
fe-1:
  nameOverride: "frontend-CHANGE_ME_CUSTOMER_ID"  # Example: frontend-prod1ks
  app:
    image:
      tag: "CHANGE_ME_FRONTEND_TAG"  # Example: 1.83.0 (update from dev version)
      pullPolicy: Always
    localConfigMaps:
      application-vars:
        # API URL should match the platform-rest-api nameOverride above
        apiUrl: "http://platform-rest-api-CHANGE_ME_CUSTOMER_ID-main/api"
        # Consul service name should match nameOverride above
        consulServiceName: "frontend-CHANGE_ME_CUSTOMER_ID"
