apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-apps
  namespace: finnplay-dev
  labels:
    environment: dev
    type: application-set
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - list:
      elements:
      - name: titan-support-services
        version: 2.63.0+build.1
        enabled: "true"
        valueFiles: ["activemq-values.yaml","apache-values.yaml","consul-values.yaml","cron-task-report-values.yaml","cron-task-values.yaml","gateway-values.yaml","nginx-values.yaml","redis-values.yaml","titan-support-services-values.yaml"]
  template:
    metadata:
      name: '{{.name}}-dev'
      namespace: finnplay-dev
      labels:
        environment: dev
        application: '{{.name}}'
      annotations:
        argocd.argoproj.io/sync-wave: "1"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: oci://ghcr.io/finnplay
        chart: '{{.name}}'
        targetRevision: '{{.version}}'
        helm:
          parameters: []
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 5m
      revisionHistoryLimit: 10
  templatePatch: |
    {{- if .valueFiles }}
    spec:
      source:
        helm:
          valueFiles:
            {{- range .valueFiles }}
            - 'https://github.com/dmitrikeler/distribution-gitops-test.git/dev/{{$.name}}/values/{{.}}'
            {{- end }}
    {{- end }}
