name: Run Tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
jobs:
  call-test-workflow:
    uses: finnplay/helm-reusables/.github/workflows/test.yaml@master
    secrets: inherit # pragma: allowlist secret
